### ISSUE TITLE
Idea: Writer trait

### ISSUE THREAD

**Issue by lkolbly** [gadomski/las-rs#19]
So I'm learning Rust and writing a little crate to interface with Livox LiDAR units, and for one of the examples I wanted to write a brief helper method to save some points. So at first I did this:
```
fn save_points(points: Vec<DataPoint>, las_writer: &mut Writer<BufWriter<File>>) {
   ... las_writer.write(p); ...
}
```
But then I thought, it'd be nice to be able to support any sort of writer, this function doesn't much care about the `BufWriter`. But there is no `Writer` trait, so you have to do something like:
```
fn save_points<T: Write + Seek + Debug>(points: Vec<DataPoint>, las_writer: &mut Writer<T>);
```
which is no fun, `save_points` doesn't care about what T implements. Would it make sense to add a `las::WriterTrait` (or maybe a `las::traits::Writer`?) which looks something like:
```
trait WriterTrait {
   fn header(&self) -> &Header;
   fn write(&mut self, point: Point) -> Result<()>;
   fn close(&mut self) -> Result<()>;
}
```
So that you can do:
```
use las::WriterTrait;
fn save_points<T: WriterTrait>(points: Vec<DataPoint>, las_writer: &mut T);
```
(really, I only care about the `write()` method right now, but `header()` and `close()` could be useful as well)

Does this seem reasonable? If so I can throw together a PR real quick.

**Comment by gadomski** [comment]
Yes, sounds very reasonable! I'd make two tweaks, just off the top of my head:
- The trait can just be named `las::Writer` instead of `WriterTrait`.
- Would it make sense to make a `Reader` trait as well?

Thanks for the thought and the engagement!

**Comment by lkolbly** [comment]
A `Reader` trait I think would make a lot of sense as well, at a quick glance `header` `read` `seek` and `points` all seem like they could live in a trait.

Since the existing struct is named `las::Writer`, (well, `las::writer::Writer` but re-exported), I don't think we could name the trait `las::Writer` without renaming the existing struct? (and breaking existing clients). But we could name the original struct to something else.

**Comment by gadomski** [comment]
> But we could name the original struct to something else.

I haven't given a ton of thought so I'm not sure if this is reasonable, but would it make sense to mirror the standard library and go with two traits, `Reader` and `Writer`, and then a single struct, `las::File`, that `impl`s both `Reader` and `Writer`?

> and breaking existing clients

I wouldn't worry about that, that's what versions are for!

**Comment by lkolbly** [comment]
I like the notion that there could be separate method names to open a `las::File` for reading (`File::open`) and a different one for writing `File::create` - when I started using this library it was unclear to me whether or not the file is truncated when written to. (and a `File::append` wouldn't be out of the ordinary if someone needed that in the future)

But what would the semantics be if a function took a `&mut las::File`? Should it be able to both read from and write to the same file? (I'm told, but I haven't tested, that the standard library throws errors if you e.g. read from a file opened in create mode. I'm less a fan of the type-safety of that approach, but maybe that's okay)

**Comment by gadomski** [comment]
> But what would the semantics be if a function took a `&mut las::File`? 

I can't come up with a good answer to this question, which maybe indicates I'm on the wrong track. Thanks for thinking that one through.

I'd be ready to look at a PR and see how this idea shakes into place, because the main idea makes sense to me. Thanks for engaging on this!
