### ISSUE TITLE
Reader API broken between v0.6.1 and v0.6.2 on crates.io

### ISSUE THREAD

**Issue by vadixidav** [gadomski/las-rs#21]
I got an API breakage downstream (internal repository at work) because of the change:

`pub struct Reader<R: Read + Seek>` -> `pub struct Reader`

Since the template argument was removed, this was a breaking change. I would consider releasing it as version 0.7.0 and yanking 0.6.2 to avoid breakage due to Cargo's semver based automatic updating.

**Comment by gadomski** [comment]
Yup, I see that happened in 6d9a4d0802ff64becdee0a4a3f6b8c3f0d2c996e. Thanks for bringing this to my attention!
