### ISSUE TITLE
Upgrade to `laz-rs` version 0.3.0

### ISSUE THREAD

**Issue by Mortano** [gadomski/las-rs#22]
This project is referencing version `0.1.0` of [`laz-rs`](https://github.com/tmontaigu/laz-rs). I encountered [some issues when reading certain LAZ files](https://github.com/tmontaigu/laz-rs/issues/13) due to the older version. Would you be willing to upgrade to version `0.3.0` of `laz-rs`? 

Note: I tried this locally, it requires some minor changes (adding lifetime specifiers) in `mod.rs` but then everything seems to work. I would be happy to open a pull request for this.

**Comment by gadomski** [comment]
A pull request would be welcome!

**Comment by gadomski** [comment]
Closed by 4a2a4bacb0e65307cb7d14195eb847bfe9be3c2b and is in v0.7.1.
