### ISSUE TITLE
Add support for VLR descriptions with non-UTF8 encoding

### ISSUE THREAD

**Issue by sebcrozet** [gadomski/las-rs#24]
The following LAS file fails to parse: https://github.com/sebcrozet/las-rs/raw/master/tests/data/test.las
The error is ` Utf8(Utf8Error { valid_up_to: 6, error_len: Some(1) })', src/libcore/result.rs:1188:5`

After some digging, I found out the problem lies in the `description` field of some variable length records. It appears those descriptions are not valid Utf8 strings. Though according to the LAS specification the `Description` field of Variable Length Records is:

> Description: Optional, null terminated text description of the data.  Any remaining characters not used must be null. 

Because the specification does not state anything about the encoding of this text, I would expect that any array of bytes terminated by a null to be considered valid. Could the parser relax its requirement on this description field? It is quite unfortunate that this problem on an optional field makes the whole parsing fail.

**Comment by gadomski** [comment]
You could make an argument that the phrase "text description" requires those bytes to be parseable as a readable string, no?

**Comment by gadomski** [comment]
However, we could drop those bytes on the floor if they're not parseable, so we can still read the file, we just lose the (non-sensical, IMO) description?

**Comment by sebcrozet** [comment]
> However, we could drop those bytes on the floor if they're not parseable, so we can still read the file, we just lose the (non-sensical, IMO) description?

I think that would make sense, yes. In [my temporary fork](https://github.com/sebcrozet/las-rs/commit/1d00458e52330d3ffbab08f9b94853831942f838) I replaced the call to `::from_utf8` to `::from_utf8_lossy` in order to still get some kind of description. Though this implies an allocation whenever the string contains invalid characters.
