### ISSUE TITLE
Support for WKT CRS (global encoding bit 4) not avaialble for point types 0-5

### ISSUE THREAD

**Issue by georgeboot** [gadomski/las-rs#66]
I believe support for WKT CRSes is missing. This is enabled for all new point types (6-10) and optional for the other point types (0-5).

In the [current implementation](https://github.com/gadomski/las-rs/blob/bea51e5a28b2f15e1ffe8503d94c591d827deace/src/header/mod.rs#L537-L539), this bit is set only for the point types 6-10, but it should also be available for point types 0-5.

https://github.com/gadomski/las-rs/blob/bea51e5a28b2f15e1ffe8503d94c591d827deace/src/header/mod.rs#L537-L539

**Comment by gadomski** [comment]
Good catch, thanks! Fix in https://github.com/gadomski/las-rs/pull/67.
