### ISSUE TITLE
LAZ support

### ISSUE THREAD

**Issue by tomjakubowski** [gadomski/las-rs#9]
Hi! :wave: First off, thanks so much for writing this library 😍 

I was wondering if you would consider adding LASzip (LAZ) support, or would accept a pull request implementing support for it. I noticed that the library [explicitly punts](https://github.com/gadomski/las-rs/blob/f873e4d2fd3a4aaadb4d3508dc07bbcc239950c0/src/reader.rs#L36-L38) on LAZ, but wasn't sure if this was for lack of time or a lack of desire to implement/support this feature.

**Comment by gadomski** [comment]
> lack of time

This one...I'd be very happy for a patch, as I'm not sure if I'll have enough time in the near future to add laz. I'd of course love a pure-Rust implementation, but would be ok with a dependency on upstream Rust bindings to [laszip](http://www.laszip.org/).

I'll keep this issue open to track any progress or additional questions.

**Comment by gadomski** [comment]
NB https://github.com/gadomski/laszip-sys exists, but isn't published on crates yet.

**Comment by gadomski** [comment]
Closed by #16
