### ISSUE TITLE
Error reading laz file, NotZeroFilled

### ISSUE THREAD

**Issue by antbern** [gadomski/las-rs#97]
Hello! I am trying to read a `laz`  file created and provided by the "Landesamt für Digitalisierung, Breitband und Vermessung"  (LDBV) in Bayern, Germany but keep hitting the following error:
```
NotZeroFilled([76, 68, 66, 86, 32, 45, 32, 76, 97, 115, 87, 1, 0, 0, 0, 0, 0, 0, 0, 252, 57, 162, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0])
```
It seems to originate from the [`as_las_str`](https://github.com/gadomski/las-rs/blob/96ef6ed59955d76f68a8db2a178110983858a11a/src/utils.rs#L24) in `utils.rs` and caused by the file not following the spec for the header (I presume). Treating the bytes as ASCII the first section before the null bytes indeed translate to "LDBV - LasW". Is there a way to disable this check and do some kind of lossy conversion instead? The point data itself is not problematic as I am able to open and view the file with for example `potree`.

The file can be downloaded [here](https://geodaten.bayern.de/odd_data/laser/803_5447.laz) (~280 MB)

**Comment by gadomski** [comment]
Thanks for the report! Should be fixed in https://github.com/gadomski/las-rs/releases/tag/v0.9.2

**Comment by antbern** [comment]
Works wonderfully, thanks for the quick fix! 💯
